### ISSUE TITLE
Amplified_Prediction_script copy.Rmd

### ISSUE THREAD

**Issue by kad-ecoli** [pylelab/MRTModSeq#1]
A few suggestions on the code:
* Please remove unnecessary library inclusion. For example, library(readxl) is unnecessary given that excel input are no longer used. In fact, you only use ``dplyr`` and ``foreign``.
* Line 25 ``Amplified-TRNA-Huh-5_8S_Untreated_5_8_mutation_counts.txtt`` should probably be changed to ``Amplified-TRNA-Huh-5_8S_Untreated_5_8_mutation_counts.txt``
* Please try to avoid space in the file name and folder name, as spaces create unnecessary difficulties for typing in the command line.
* The line ``@attribute Modifications `` should be automatically written rather than manually changed by the user.

**Comment by kad-ecoli** [comment]
```R
ratesfun <- function(x,y) {
  x / y
}
```
Should we consider case where y==0?

**Comment by kad-ecoli** [comment]
[Amplified_Prediction_script.R.zip](https://github.com/pylelab/MRTModSeq/files/8703314/Amplified_Prediction_script.R.zip)
Please see an example where the command line argument is used to specified the input file name. To run the program:
```bash
mkdir test
cd test

Rscript  ../Amplified_Prediction_script.R "../sample 5.8S rRNA data input and output/amplified_predictions_script INPUTS/Amplified-TRNA-Huh-5_8S_5_8_profile.txt" "../sample 5.8S rRNA data input and output/amplified_predictions_script INPUTS/Amplified-TRNA-Huh-5_8S_Untreated_5_8_mutation_counts.txt" "../sample 5.8S rRNA data input and output/amplified_predictions_script INPUTS/Amplified-TRNA-Huh-5_8S_Modified_5_8_mutation_counts.txt"
```

Here, only the input file names are specified by command line arguments, while output file names are hard coded, which should not be a big problem so long as the output is in the current folder.

**Comment by pylelab** [comment]
Thank you so much Chengxin! Huge help. Have made some small changes, and have also added the output_reordering.r file.
