### ISSUE TITLE
inconsistent predict_5_8_guanine_amp.arff

### ISSUE THREAD

**Issue by kad-ecoli** [pylelab/MRTModSeq#2]
According to line 287 of https://github.com/pylelab/MRTModSeq/blob/main/Amplified_Prediction_script%20copy.Rmd
```R
tx_line15 <- gsub(pattern = "'\\?'", replace = "none,Gm", x = tx[15])
```
The output labels should be
```
@attribute Modifications {none,Gm} 
```
However, in https://github.com/pylelab/MRTModSeq/blob/main/sample%205.8S%20rRNA%20data%20input%20and%20output/amplified_prediction_script_OUTPUTS/predict_5_8_guanine_amp.arff, the output label is actually
```
@attribute Modifications {Gm,none}
```
Is this a bug?

**Comment by pylelab** [comment]
yes! fixing it now.
